[package]
name = "uasset_utils"
version.workspace = true
edition.workspace = true

[dependencies]
unreal_asset = { workspace = true }
anyhow = { workspace = true }
byteorder = "1.5.0"
ser-hex = { version = "0.1.0", path = "../../ser-hex/ser-hex" }
tracing = "0.1.40"
