macro_rules! inst {
    ($name:ident, $( $a:tt )* ) => {
        struct $name {
            $( $a: i32, )*
        }
    };
}

macro_rules! braces_unwrap {
    ( $Callback:path, $name:ident, $( $Src : tt )* ) => {
        $Callback!
        (
            $name,
            $( $Src )*
        );
    };
}

macro_rules! for_each {
    ( $( $name:ident { $( $Each : tt ),* $(,)?} ),* $(,)?) => {
        mod a {
            $( braces_unwrap!( inst, $name, $($Each)* );)*
        }
        mod b {
            $( braces_unwrap!( inst, $name, $($Each)* );)*
        }
    };
}

for_each!(
    ExLocalVariable { a, b },
    ExInstanceVariable { a },
    ExDefaultVariable { b },
);

//for_each!( ExLocalVariable, ExInstanceVariable, ExDefaultVariable,);

/*
for_each!(
    ExLocalVariable {},
    ExInstanceVariable {},
    ExDefaultVariable {},
    ExReturn {},
    ExJump {},
    ExJumpIfNot {},
    ExAssert {},
    ExNothing {},
    ExLet {},
    ExClassContext {},
    ExMetaCast {},
    ExLetBool {},
    ExEndParmValue {},
    ExEndFunctionParms {},
    ExSelf {},
    ExSkip {},
    ExContext {},
    ExContextFailSilent {},
    ExVirtualFunction {},
    ExFinalFunction {},
    ExIntConst {},
    ExFloatConst {},
    ExStringConst {},
    ExObjectConst {},
    ExNameConst {},
    ExRotationConst {},
    ExVectorConst {},
    ExByteConst {},
    ExIntZero {},
    ExIntOne {},
    ExTrue {},
    ExFalse {},
    ExTextConst {},
    ExNoObject {},
    ExTransformConst {},
    ExIntConstByte {},
    ExNoInterface {},
    ExDynamicCast {},
    ExStructConst {},
    ExEndStructConst {},
    ExSetArray {},
    ExEndArray {},
    ExPropertyConst {},
    ExUnicodeStringConst {},
    ExInt64Const {},
    ExUInt64Const {},
    ExPrimitiveCast {},
    ExSetSet {},
    ExEndSet {},
    ExSetMap {},
    ExEndMap {},
    ExSetConst {},
    ExEndSetConst {},
    ExMapConst {},
    ExEndMapConst {},
    ExStructMemberContext {},
    ExLetMulticastDelegate {},
    ExLetDelegate {},
    ExLocalVirtualFunction {},
    ExLocalFinalFunction {},
    ExLocalOutVariable {},
    ExDeprecatedOp4A {},
    ExInstanceDelegate {},
    ExPushExecutionFlow {},
    ExPopExecutionFlow {},
    ExComputedJump {},
    ExPopExecutionFlowIfNot {},
    ExBreakpoint {},
    ExInterfaceContext {},
    ExObjToInterfaceCast {},
    ExEndOfScript {},
    ExCrossInterfaceCast {},
    ExInterfaceToObjCast {},
    ExWireTracepoint {},
    ExSkipOffsetConst {},
    ExAddMulticastDelegate {},
    ExClearMulticastDelegate {},
    ExTracepoint {},
    ExLetObj {},
    ExLetWeakObjPtr {},
    ExBindDelegate {},
    ExRemoveMulticastDelegate {},
    ExCallMulticastDelegate {},
    ExLetValueOnPersistentFrame {},
    ExArrayConst {},
    ExEndArrayConst {},
    ExSoftObjectConst {},
    ExCallMath {},
    ExSwitchValue {},
    ExInstrumentationEvent {},
    ExArrayGetByRef {},
    ExClassSparseDataVariable {},
    ExFieldPathConst {},
);
*/
/*
for_each!(
    ExLocalVariable,
    ExInstanceVariable,
    ExDefaultVariable,
    ExReturn,
    ExJump,
    ExJumpIfNot,
    ExAssert,
    ExNothing,
    ExLet,
    ExClassContext,
    ExMetaCast,
    ExLetBool,
    ExEndParmValue,
    ExEndFunctionParms,
    ExSelf,
    ExSkip,
    ExContext,
    ExContextFailSilent,
    ExVirtualFunction,
    ExFinalFunction,
    ExIntConst,
    ExFloatConst,
    ExStringConst,
    ExObjectConst,
    ExNameConst,
    ExRotationConst,
    ExVectorConst,
    ExByteConst,
    ExIntZero,
    ExIntOne,
    ExTrue,
    ExFalse,
    ExTextConst,
    ExNoObject,
    ExTransformConst,
    ExIntConstByte,
    ExNoInterface,
    ExDynamicCast,
    ExStructConst,
    ExEndStructConst,
    ExSetArray,
    ExEndArray,
    ExPropertyConst,
    ExUnicodeStringConst,
    ExInt64Const,
    ExUInt64Const,
    ExPrimitiveCast,
    ExSetSet,
    ExEndSet,
    ExSetMap,
    ExEndMap,
    ExSetConst,
    ExEndSetConst,
    ExMapConst,
    ExEndMapConst,
    ExStructMemberContext,
    ExLetMulticastDelegate,
    ExLetDelegate,
    ExLocalVirtualFunction,
    ExLocalFinalFunction,
    ExLocalOutVariable,
    ExDeprecatedOp4A,
    ExInstanceDelegate,
    ExPushExecutionFlow,
    ExPopExecutionFlow,
    ExComputedJump,
    ExPopExecutionFlowIfNot,
    ExBreakpoint,
    ExInterfaceContext,
    ExObjToInterfaceCast,
    ExEndOfScript,
    ExCrossInterfaceCast,
    ExInterfaceToObjCast,
    ExWireTracepoint,
    ExSkipOffsetConst,
    ExAddMulticastDelegate,
    ExClearMulticastDelegate,
    ExTracepoint,
    ExLetObj,
    ExLetWeakObjPtr,
    ExBindDelegate,
    ExRemoveMulticastDelegate,
    ExCallMulticastDelegate,
    ExLetValueOnPersistentFrame,
    ExArrayConst,
    ExEndArrayConst,
    ExSoftObjectConst,
    ExCallMath,
    ExSwitchValue,
    ExInstrumentationEvent,
    ExArrayGetByRef,
    ExClassSparseDataVariable,
    ExFieldPathConst,
);
*/
